# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "disk_vhd1"
edition.workspace = true
rust-version.workspace = true

[dependencies]
disk_file.workspace = true
disk_backend.workspace = true
disk_backend_resources.workspace = true
scsi_buffers.workspace = true
vhd1_defs.workspace = true
guestmem.workspace = true
vm_resource.workspace = true

guid = { workspace = true, features = ["inspect"] }
inspect.workspace = true
pal_async.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]

[target.'cfg(target_os = "linux")'.dependencies]

[lints]
workspace = true
