# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "underhill_attestation"
edition.workspace = true
rust-version.workspace = true

[features]
# Enable locally compiling and statically linking a copy of OpenSSL.
# The build process requires a C compiler, perl, and make.
openssl-vendored = ["openssl/vendored"]

[target.'cfg(target_os = "linux")'.dependencies]
guest_emulation_transport.workspace = true
openhcl_attestation_protocol.workspace = true
vmgs = { workspace = true, features = ["encryption_ossl"] }
guid.workspace = true
mesh.workspace = true
openssl_kdf.workspace = true
tee_call.workspace = true
pal_async.workspace = true
tracing.workspace = true
cvm_tracing.workspace = true

base64.workspace = true
base64-serde.workspace = true
getrandom.workspace = true
openssl.workspace = true
serde_json.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["macros"] }
zerocopy.workspace = true
[target.'cfg(target_os = "linux")'.dev-dependencies]
disklayer_ram.workspace = true
disk_backend.workspace = true
get_protocol.workspace = true
vmgs_format.workspace = true

[lints]
workspace = true
