# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "virt_kvm"
edition.workspace = true
rust-version.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
virt.workspace = true

aarch64defs.workspace = true
bitfield-struct.workspace = true
hv1_emulator.workspace = true
hv1_hypercall.workspace = true
hvdef.workspace = true
kvm.workspace = true
pci_core.workspace = true
guestmem.workspace = true
open_enum.workspace = true
vmcore.workspace = true
memory_range.workspace = true
vm_topology.workspace = true
x86defs.workspace = true

cfg-if.workspace = true
safe_intrinsics.workspace = true
inspect.workspace = true
pal_event.workspace = true

parking_lot.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracelimit.workspace = true
zerocopy.workspace = true
[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
