# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "hyperv_ic_guest"
edition.workspace = true
rust-version.workspace = true

[dependencies]
hyperv_ic_protocol.workspace = true
hyperv_ic_resources.workspace = true
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_core.workspace = true
vmbus_relay_intercept_device.workspace = true
vmbus_ring.workspace = true
vmcore.workspace = true

inspect.workspace = true
mesh.workspace = true
task_control.workspace = true
guid.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
zerocopy.workspace = true
[dev-dependencies]

[lints]
workspace = true
