# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "framebuffer"
edition = "2021"
rust-version.workspace = true

[dependencies]
video_core.workspace = true
vm_resource.workspace = true

chipset_device.workspace = true
guestmem.workspace = true
vmcore.workspace = true
memory_range = { workspace = true, features = ["mesh", "inspect"] }

inspect.workspace = true
mesh.workspace = true
sparse_mmap.workspace = true

anyhow.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[lints]
workspace = true
