# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_core"
edition = "2021"
rust-version.workspace = true

[dependencies]
hvdef.workspace = true
inspect.workspace = true
guid = { workspace = true, features = ["inspect"] }
mesh.workspace = true
open_enum.workspace = true

bitfield-struct.workspace = true
futures.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
zerocopy_helpers.workspace = true

[lints]
workspace = true
