# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "disk_backend_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
vm_resource.workspace = true

mesh.workspace = true

[lints]
workspace = true
