# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "task_control"
edition = "2021"
rust-version.workspace = true

[dependencies]
fast_select.workspace = true
inspect = { workspace = true, features = ["defer", "std"] }
pal_async.workspace = true

parking_lot.workspace = true

[dev-dependencies]
futures.workspace = true

[lints]
workspace = true
