# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "hv1_hypercall"
edition = "2021"
rust-version.workspace = true

[dependencies]
hvdef.workspace = true
guestmem.workspace = true
tracelimit.workspace = true

thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[dev-dependencies]
open_enum.workspace = true
sparse_mmap.workspace = true
test_with_tracing.workspace = true

[lints]
workspace = true
