# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "hcl_compat_uefi_nvram_storage"
edition.workspace = true
rust-version.workspace = true

[features]
default = []

inspect = ["dep:inspect", "uefi_nvram_storage/inspect"]

[dependencies]
uefi_nvram_storage.workspace = true

guid.workspace = true
inspect = { workspace = true, optional = true }
open_enum.workspace = true
ucs2.workspace = true

anyhow.workspace = true
async-trait.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
tracing.workspace = true
wchar.workspace = true
zerocopy.workspace = true
[dev-dependencies]
pal_async.workspace = true

[lints]
workspace = true
