# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tmk_tests"
rust-version.workspace = true
edition.workspace = true

[dependencies]
petri.workspace = true
petri_artifacts_common.workspace = true
petri_artifacts_vmm_test.workspace = true

pal_async.workspace = true

anyhow.workspace = true
tracing.workspace = true

[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
