# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vbs_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
bitfield-struct.workspace = true
igvm_defs.workspace = true
open_enum.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
