# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tee_call"
edition.workspace = true
rust-version.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
sev_guest_device.workspace = true
tdx_guest_device.workspace = true

static_assertions.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
[lints]
workspace = true
