# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmm_test_petri_support"
edition = "2021"
rust-version.workspace = true

[dependencies]
petri_artifacts_vmm_test.workspace = true

petri_artifacts_common.workspace = true
petri.workspace = true

anyhow.workspace = true
parking_lot.workspace = true

[lints]
workspace = true
