# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vmbus_relay"
edition = "2021"
rust-version.workspace = true

[dependencies]
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_client.workspace = true
vmbus_core.workspace = true
vmbus_server.workspace = true

guid.workspace = true
hvdef.workspace = true
vmcore.workspace = true
hcl.workspace = true
inspect.workspace = true
mesh.workspace = true
mesh_protobuf.workspace = true
pal_event.workspace = true
pal_async.workspace = true
tracelimit.workspace = true

anyhow.workspace = true
futures.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
