# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vmbus_proxy"
edition = "2021"
rust-version.workspace = true

[target.'cfg(windows)'.dependencies]
guestmem.workspace = true
vmbus_core.workspace = true

mesh.workspace = true
pal.workspace = true
pal_event.workspace = true
pal_async.workspace = true

ntapi.workspace = true
winapi = { workspace = true, features = ["debug", "winioctl"] }
zerocopy.workspace = true

[lints]
workspace = true
