# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_proxy"
edition.workspace = true
rust-version.workspace = true

[target.'cfg(windows)'.dependencies]
guestmem.workspace = true
vmbus_core.workspace = true

mesh.workspace = true
pal.workspace = true
pal_event.workspace = true
pal_async.workspace = true

futures.workspace = true
ntapi.workspace = true
tracing.workspace = true
winapi = { workspace = true, features = ["debug", "winioctl"] }
zerocopy.workspace = true
[lints]
workspace = true
