# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "make_imc_hive"
edition = "2021"
rust-version.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Wdk_System_OfflineRegistry", "Win32_Foundation", "Win32_Security", "Win32_System_Registry"] }

anyhow.workspace = true

[lints]
workspace = true
