# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "gdma_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
net_backend_resources.workspace = true
vm_resource.workspace = true

mesh.workspace = true

[lints]
workspace = true
