# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "nvme_driver"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect = { workspace = true, features = ["defer"] }
inspect_counters.workspace = true
mesh.workspace = true
pal_async.workspace = true
nvme_spec.workspace = true
task_control.workspace = true
user_driver.workspace = true
guestmem.workspace = true
vmcore.workspace = true

anyhow.workspace = true
event-listener.workspace = true
futures.workspace = true
parking_lot.workspace = true
safeatomic.workspace = true
slab.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[dev-dependencies]
chipset_device.workspace = true
disk_ramdisk.workspace = true
nvme.workspace = true
pci_core.workspace = true
scsi_buffers.workspace = true
test_with_tracing.workspace = true

guid.workspace = true

[lints]
workspace = true
