# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vmbfs"
edition = "2021"
rust-version.workspace = true

[dependencies]
vmbfs_resources.workspace = true
vm_resource.workspace = true

vmbus_async.workspace = true
vmbus_channel.workspace = true
vmcore.workspace = true

guid.workspace = true
inspect = { workspace = true, features = ["filepath"] }
open_enum.workspace = true
task_control.workspace = true

async-trait.workspace = true
bitfield-struct.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true
zerocopy_helpers.workspace = true

[lints]
workspace = true
