# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "disk_file"
edition = "2021"
rust-version.workspace = true

[dependencies]
disk_backend.workspace = true
disk_backend_resources.workspace = true
scsi_buffers.workspace = true
guestmem.workspace = true
vm_resource.workspace = true

inspect = { workspace = true, features = ["filepath"] }
blocking.workspace = true
stackfuture.workspace = true

[lints]
workspace = true
