# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "guest_crash_device"
edition.workspace = true
rust-version.workspace = true

[dependencies]
get_protocol.workspace = true
get_resources.workspace = true
guestmem.workspace = true
guid.workspace = true
inspect.workspace = true
mesh.workspace = true
task_control.workspace = true
vmbus_channel.workspace = true
vmbus_async.workspace = true
vmcore.workspace = true
vm_resource.workspace = true

anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true
zerocopy.workspace = true
[lints]
workspace = true
