# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition.workspace = true
name = "igvmfilegen"
rust-version.workspace = true

[dependencies]
igvmfilegen_config.workspace = true
loader.workspace = true
loader_defs.workspace = true

hvdef.workspace = true

memory_range.workspace = true
underhill_confidentiality.workspace = true
vbs_defs.workspace = true
x86defs.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
fs-err.workspace = true
hex = { workspace = true, features = ["serde"] }
igvm.workspace = true
igvm_defs.workspace = true
range_map_vec.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
zerocopy.workspace = true
[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.build-dependencies]
loader_defs.workspace = true

[lints]
workspace = true
