# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "safeatomic"
edition.workspace = true
rust-version.workspace = true

[dependencies]
zerocopy.workspace = true
[lints]
workspace = true
