# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "clap_dyn_complete"
edition = "2021"
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
futures.workspace = true
log.workspace = true

[lints]
workspace = true
