# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vm_topology"
edition = "2021"
rust-version.workspace = true

[features]
default = []
inspect = ["dep:inspect", "memory_range/inspect"]
mesh = ["dep:mesh_protobuf", "memory_range/mesh"]

[dependencies]
aarch64defs.workspace = true
memory_range.workspace = true
safe_x86_intrinsics.workspace = true
inspect = { workspace = true, optional = true }
mesh_protobuf = { workspace = true, optional = true }
x86defs.workspace = true

cfg-if.workspace = true
thiserror.workspace = true

[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
