# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "uefi_nvram_specvars"
edition = "2021"
rust-version.workspace = true

[features]
default = []

[dependencies]
guid.workspace = true
ucs2.workspace = true
uefi_specs.workspace = true
zerocopy_helpers.workspace = true

thiserror.workspace = true
zerocopy.workspace = true

[dev-dependencies]

[lints]
workspace = true
