# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "mesh_build"
edition = "2021"
rust-version.workspace = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
prost-build.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
