# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "guest_emulation_device"
edition.workspace = true
rust-version.workspace = true

[features]
test_utilities = ["dep:disklayer_ram"]

[dependencies]
get_protocol.workspace = true
get_resources.workspace = true

disk_backend.workspace = true
disklayer_ram = { workspace = true, optional = true }
guestmem.workspace = true
openhcl_attestation_protocol.workspace = true
power_resources.workspace = true
scsi_buffers.workspace = true
video_core.workspace = true
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_ring.workspace = true
vmcore.workspace = true
vm_resource.workspace = true

async-trait.workspace = true
inspect.workspace = true
mesh.workspace = true
pal_async.workspace = true
task_control.workspace = true
tracelimit.workspace = true

futures.workspace = true
parking_lot.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["local-offset", "macros"] }
tracing.workspace = true
zerocopy.workspace = true
guid.workspace = true

[lints]
workspace = true
