# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "guest_emulation_device"
edition = "2021"
rust-version.workspace = true

[dependencies]
get_protocol.workspace = true
get_resources.workspace = true

power_resources.workspace = true
video_core.workspace = true
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_ring.workspace = true
vmcore.workspace = true
vm_resource.workspace = true

async-trait.workspace = true
inspect.workspace = true
mesh.workspace = true
pal_async.workspace = true
task_control.workspace = true

futures.workspace = true
parking_lot.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["local-offset", "macros"] }
tracing.workspace = true
zerocopy.workspace = true
zerocopy_helpers.workspace = true

guid.workspace = true

[lints]
workspace = true
