# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "disk_ramdisk"
edition = "2021"
rust-version.workspace = true

[dependencies]
disk_backend.workspace = true
disk_backend_resources.workspace = true
guestmem.workspace = true
scsi_buffers.workspace = true
vm_resource.workspace = true

inspect.workspace = true
pal_async.workspace = true

anyhow.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
event-listener.workspace = true
stackfuture.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
