# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "fast_select"
edition = "2021"
rust-version.workspace = true

[dependencies]
parking_lot.workspace = true

[dev-dependencies]
futures.workspace = true
pal_async.workspace = true

[lints]
workspace = true

[package.metadata.xtask.unused-deps]
# Used in doc tests
ignored = ["futures"]
