# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "virt_whp"
edition.workspace = true
rust-version.workspace = true

[features]
unstable_whp = ["whp/unstable_whp"]

[target.'cfg(windows)'.dependencies]
aarch64defs.workspace = true
chipset_device.workspace = true
hv1_emulator.workspace = true
hv1_hypercall.workspace = true
hv1_structs.workspace = true
hvdef.workspace = true
pci_core.workspace = true
memory_range = { workspace = true, features = ["inspect"] }
vm_topology = { workspace = true, features = ["inspect"] }
guestmem.workspace = true
vmcore.workspace = true
virt.workspace = true
virt_support_aarch64emu.workspace = true
virt_support_apic.workspace = true
virt_support_x86emu.workspace = true
whp.workspace = true
x86defs.workspace = true
x86emu.workspace = true

inspect = { workspace = true, features = ["std"] }
inspect_counters.workspace = true
mesh.workspace = true
pal_event.workspace = true
range_map_vec.workspace = true
sparse_mmap.workspace = true
tracelimit.workspace = true
tracing_helpers.workspace = true

anyhow.workspace = true
arrayvec.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tracing.workspace = true
winapi.workspace = true
zerocopy.workspace = true
[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
