# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "debug_worker_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
vmm_core_defs.workspace = true

mesh.workspace = true
mesh_worker.workspace = true
vmsocket.workspace = true

[lints]
workspace = true
