# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "underhill_confidentiality"
edition = "2021"
rust-version.workspace = true

[features]
std = []

[lints]
workspace = true
