# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "disk_striped"
edition = "2021"
rust-version.workspace = true

[dependencies]
disk_backend.workspace = true
disk_backend_resources.workspace = true
scsi_buffers.workspace = true

anyhow.workspace = true
async-trait.workspace = true
hvdef.workspace = true
guestmem.workspace = true
inspect.workspace = true
pal_async.workspace = true
futures.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
vm_resource.workspace = true

[dev-dependencies]
disk_ramdisk.workspace = true

[lints]
workspace = true
