# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_user_channel"
edition.workspace = true
rust-version.workspace = true

[target.'cfg(unix)'.dependencies]
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_ring.workspace = true

guid.workspace = true
pal_async.workspace = true
safeatomic.workspace = true
sparse_mmap.workspace = true

filepath.workspace = true
fs-err.workspace = true
libc.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true
[lints]
workspace = true
