# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "ide"
edition.workspace = true
rust-version.workspace = true

[dependencies]
chipset_device.workspace = true
disk_backend.workspace = true
ide_resources.workspace = true
inspect.workspace = true
mesh.workspace = true
open_enum.workspace = true
pal_async.workspace = true
pci_core.workspace = true
safeatomic.workspace = true
scsi_buffers.workspace = true
scsi_core.workspace = true
scsi_defs.workspace = true
scsidisk.workspace = true
test_with_tracing.workspace = true
tracing_helpers.workspace = true
guestmem.workspace = true
vmcore.workspace = true

bitfield-struct.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
zerocopy.workspace = true
[dev-dependencies]
disk_file.workspace = true

tempfile.workspace = true

[lints]
workspace = true
