# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "serde_helpers"
edition = "2021"
rust-version.workspace = true

[dependencies]
guid.workspace = true

base64.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lints]
workspace = true
