# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "pal"
edition.workspace = true
rust-version.workspace = true

[features]
# Disable tests that do not pass in the CI environment.
ci = []
sandbox_tests = []

[build-dependencies]
win_import_lib.workspace = true

[dependencies]
getrandom.workspace = true

[target.'cfg(windows)'.dependencies]
pal_event.workspace = true

ntapi = { workspace = true, features = ["impl-default"] }
socket2 = { workspace = true, features = ["all"] }
widestring.workspace = true

[target.'cfg(windows)'.dependencies.winapi]
workspace = true
features = [
    "errhandlingapi",
    "fileapi",
    "handleapi",
    "heapapi",
    "ioapiset",
    "impl-default",
    "jobapi2",
    "memoryapi",
    "namedpipeapi",
    "ntstatus",
    "processenv",
    "processthreadsapi",
    "sddl",
    "securitybaseapi",
    "std",
    "synchapi",
    "threadpoolapiset",
    "winbase",
    "winerror",
    "winioctl",
    "winnt",
    "winsock2",
]

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Wdk_Foundation", 
    "Win32_Foundation",
    "Win32_Security"
]

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
caps.workspace = true
seccompiler.workspace = true
landlock.workspace = true
fs-err.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
