# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "disk_backend"
edition = "2021"
rust-version.workspace = true

[dependencies]
scsi_buffers.workspace = true

guestmem.workspace = true
vm_resource.workspace = true
inspect = { workspace = true, features = ["std"] }

async-trait.workspace = true
futures.workspace = true
stackfuture.workspace = true
thiserror.workspace = true

[lints]
workspace = true
