# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "lxutil"
edition.workspace = true
rust-version.workspace = true

[features]
# Disable tests that do not pass in the CI environment.
ci = []

[dependencies]
lx.workspace = true

pal.workspace = true

tracing.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
bitfield-struct.workspace = true
ntapi.workspace = true
parking_lot.workspace = true
static_assertions.workspace = true
widestring.workspace = true
zerocopy.workspace = true
[target.'cfg(windows)'.dependencies.winapi]
workspace = true
features = [
    "basetsd",
    "consoleapi",
    "handleapi",
    "memoryapi",
    "namedpipeapi",
    "processenv",
    "realtimeapiset",
    "synchapi",
    "winbase",
    "wincon",
    "winnls",
    "winnt",
    "winsock2",
]

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [ 
    "Wdk_Foundation",
    "Wdk_Storage_FileSystem",
    "Wdk_System_SystemServices",
    "Wdk_System_Threading",
    "Win32_Foundation", 
    "Win32_Security", 
    "Win32_Storage_FileSystem", 
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
]

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
