# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_client"
edition.workspace = true
rust-version.workspace = true

[dependencies]
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_core.workspace = true

guid.workspace = true
mesh.workspace = true
pal_async.workspace = true
pal_event.workspace = true
inspect.workspace = true

anyhow.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true
[dev-dependencies]
parking_lot.workspace = true
pal_async.workspace = true

[lints]
workspace = true
