# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_client"
edition.workspace = true
rust-version.workspace = true

[dependencies]
user_driver.workspace = true
vmbus_async.workspace = true
vmbus_channel.workspace = true
vmbus_core.workspace = true
vmbus_ring.workspace = true
vmcore.workspace = true

guid.workspace = true
mesh.workspace = true
pal_async.workspace = true
pal_event.workspace = true
inspect.workspace = true
tracelimit.workspace = true

anyhow.workspace = true
futures.workspace = true
futures-concurrency.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[dev-dependencies]
pal_async.workspace = true
test_with_tracing.workspace = true

getrandom.workspace = true

[lints]
workspace = true
