# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "virt_mshv"
edition.workspace = true
rust-version.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
hv1_emulator.workspace = true
hv1_hypercall.workspace = true
hvdef.workspace = true
virt.workspace = true
virt_support_x86emu.workspace = true
guestmem.workspace = true
vmcore.workspace = true
x86emu.workspace = true
x86defs.workspace = true

pal.workspace = true
pal_event.workspace = true
inspect.workspace = true
tracelimit.workspace = true

mshv-bindings = { workspace = true, features = ["with-serde", "fam-wrappers"] }
mshv-ioctls.workspace = true
arrayvec.workspace = true
libc.workspace = true
parking_lot.workspace = true
signal-hook.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
tracing.workspace = true
vmm-sys-util.workspace = true
zerocopy.workspace = true
[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
