# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "uefi_specs"
edition.workspace = true
rust-version.workspace = true

[features]
default = []

inspect = ["dep:inspect"]

[dependencies]
guid.workspace = true
inspect = { workspace = true, optional = true }
open_enum.workspace = true
ucs2.workspace = true

bitfield-struct.workspace = true
static_assertions.workspace = true
wchar.workspace = true
zerocopy.workspace = true
[dev-dependencies]

[lints]
workspace = true
