# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vnc"
edition = "2021"
rust-version.workspace = true

[dependencies]
pal_async.workspace = true

futures.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
socket2 = { workspace = true, features = [ "all" ] }

[lints]
workspace = true
