# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "serial_core"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
vm_resource.workspace = true

mesh.workspace = true

futures.workspace = true
pal_async.workspace = true
parking_lot.workspace = true

[lints]
workspace = true
