# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "hv1_emulator"
edition = "2021"
rust-version.workspace = true

[dependencies]
hvdef = { workspace = true, features = ["std"] }
vm_topology.workspace = true
guestmem.workspace = true
virt.workspace = true
vmcore.workspace = true
vtl_array.workspace = true
x86defs.workspace = true

inspect.workspace = true
tracelimit.workspace = true
parking_lot.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
