# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "scsi_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
zerocopy.workspace = true
bitfield-struct.workspace = true
open_enum.workspace = true

[lints]
workspace = true
