# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "underhill_dump"
edition = "2021"
rust-version.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
elfcore.workspace = true

anyhow.workspace = true
libc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
