# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vpci"
edition.workspace = true
rust-version.workspace = true

[dependencies]
pci_core.workspace = true

device_emulators.workspace = true
vmbus_channel.workspace = true
vmbus_async.workspace = true
vmbus_ring.workspace = true

chipset_arc_mutex_device.workspace = true
chipset_device.workspace = true
guestmem.workspace = true
vmcore.workspace = true
hvdef.workspace = true

closeable_mutex.workspace = true
guid.workspace = true
inspect.workspace = true
mesh.workspace = true
open_enum.workspace = true
pal_async.workspace = true
task_control.workspace = true
test_with_tracing.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bitfield-struct.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
zerocopy.workspace = true
[lints]
workspace = true
