# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[book]
language = "en"
multilingual = false
src = "src"
title = "The OpenVMM Guide"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/microsoft/OpenVMM"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/microsoft/OpenVMM/edit/main/Guide/{path}"
