# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "hvdef"
edition = "2021"
rust-version.workspace = true

[features]
default = []
std = []

[dependencies]
open_enum.workspace = true
bitfield-struct.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
