# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "missing_dev"
edition = "2021"
rust-version.workspace = true

[dependencies]
chipset_device.workspace = true
chipset_device_resources.workspace = true
missing_dev_resources.workspace = true
pci_core.workspace = true
vmcore.workspace = true
vm_resource.workspace = true

inspect.workspace = true

[lints]
workspace = true
