# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vmgs_format"
edition = "2021"
rust-version.workspace = true

[dependencies]
open_enum.workspace = true
inspect = { workspace = true, optional = true }

bitfield-struct.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
