# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tdcall"
edition = "2021"
rust-version.workspace = true

[features]
default = []
std = []
tracing = ["std", "dep:tracing"]

[dependencies]
hvdef.workspace = true
memory_range.workspace = true
x86defs.workspace = true

tracing = { workspace = true, optional = true }

[lints]
workspace = true
