# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "guid"
edition = "2021"
rust-version.workspace = true

[features]
default = []
mesh = ["mesh_protobuf"]

[dependencies]
inspect = { workspace = true, optional = true }
mesh_protobuf = { workspace = true, optional = true }

getrandom.workspace = true
thiserror.workspace = true
zerocopy.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[target.'cfg(windows)'.dependencies.winapi]
workspace = true
features = [
    "guiddef",
]

[lints]
workspace = true
